POST http://localhost:1234/person
Content-Type: application/json

{
    {
    "status": true,
    "persona": {
        "nombre": "Pedro",
        "apellido": "Méndez",
        "edad": 36,
        "contacto": {
          "telefono": "5498761234",
          "correo": "pedro.mendez36@gmail.com"
        },
        "residencia": {
          "pais": "Perú",
          "provincia": "Lima",
          "ciudad": "Miraflores"
        }
      }
    }
}